### ISSUE TITLE
Eye button issue on login page

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal-Stephanie---Store-Redesign#12]
Bug - Password eye button not showing on login page.
Exp - Add eye button on password field on login page and reset password page.
Ref Link - https://drive.google.com/file/d/1z5v7JNfnjxb8lTxONcrkjqjc5jYZs2R6/view

**Comment by devabulabbas** [comment]
Resolved On Login Page 
Threre is no field on reset page

**Comment by ankitcedcoss** [comment]
Bug Fixed
