### ISSUE TITLE
Password verification issue on reset page.

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal-Stephanie---Store-Redesign#13]
Bug - Password char verification not same on create account and on password reset page.
Exp - Password verification should be same on reset and on create account page.
Ref Link - https://drive.google.com/file/d/1P9sdRBZvWELNBfviitxDFhLYJnkW0Qdn/view

**Comment by devabulabbas** [comment]
You Are Checking Reset Page On Live Theme 
Preview Thmeme Reset Validation is correct 
![image](https://user-images.githubusercontent.com/100209490/164603649-f346b7b7-044e-42f7-967d-8504cb6a5575.png)

**Comment by ankitcedcoss** [comment]
Bug Not Fixed
https://drive.google.com/file/d/1iSBDAUaJQZcJL49FgNmM84ekRSdGMmxU/view

**Comment by devabulabbas** [comment]
Resolved

**Comment by ankitcedcoss** [comment]
Bug Fixed
