### ISSUE TITLE
Price filter issue on collection page

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal-Stephanie---Store-Redesign#5]
Bug - On changing shopping currency then currency type not changing in price filter.
Exp - If user changes and shopping currency then currency should get change in price filter also.
Ref Link - https://drive.google.com/file/d/1OYL4St2iXXPxH_mht-SQ4YpBVQOC_SgQ/view

**Comment by devabulabbas** [comment]
@ankitcedcoss 
This wil not be able to change becasue the whole currency is chainging form app and the $ is coming frm shopify 
I have messeged the app support for this but didnt get rply yet

**Comment by ankitcedcoss** [comment]
Closed on Not required
