### ISSUE TITLE
Clear all button placement issue on cart.

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal-Stephanie---Store-Redesign#9]
Bug - Clear all button on cart page is misplaced.
Exp - Move Clear all button below checkout button on cart page.
Ref Link - https://nimb.ws/WAVMZT

**Comment by devabulabbas** [comment]
Resolved @ankitcedcoss

**Comment by ankitcedcoss** [comment]
Bug Fixed
